services:
  mlbgamethreadbot:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - TZ=America/New_York
    env_file:
      - .env
    restart: always